name: "OSCAL Validations: Integration tests"

on:
  workflow_dispatch:
    inputs:
      cli_version:
        description: 'OSCAL CLI Version'
        required: true
        default: '2.4.0'
        type: string
      oscal_repo:
        description: 'OSCAL Repository'
        required: true
        default: 'usnistgov/OSCAL'
        type: string
      oscal_branch:
        description: 'OSCAL Branch'
        required: true
        default: 'main'
        type: string

jobs:
  run-tests:
    name: "Integration Tests"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
  
      - name: Read node version from .nvmrc
        id: nvmrc
        shell: bash
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install required node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure OSCAL
        run: |
          make configure OSCAL_CLI_VERSION=${{ inputs.cli_version }} OSCAL_REPO=${{ inputs.oscal_repo }}#${{ inputs.oscal_branch }}

      - name: Run tests
        run: make test

      - name: Publish test results
        uses: test-summary/action@v1
        if: always()
        with:
          paths: "**/reports/junit-*.xml"
